CASSANDRA-17581 fix NodeProbe: Malformed IPv6 address at index
Fix error when new NodeProbe("127.0.0.1", 7199) with jdk 1.8.0_332:

```
java.io.IOException: Failed to retrieve RMIServer stub:
 javax.naming.InvalidNameException: Malformed IPv6 address at index 7: rmi://[127.0.0.1]:7199
 Root exception is java.lang.IllegalArgumentException: Malformed IPv6 address at index 7: rmi://[127.0.0.1]:7199
```

Ref: https://github.com/apache/cassandra/pull/1586
Ref: https://issues.apache.org/jira/projects/CASSANDRA/issues/CASSANDRA-17581
Ref: https://www.oracle.com/java/technologies/javase/8u331-relnotes.html#JDK-8278972
Ref: https://community.datastax.com/questions/13764/java-version-for-cassandra-3113.html

Closes #295

(cherry picked from commit a4573759a2bbf47ef46fadd511601fca2a36b127)