dist/redhat: Add "python-yaml" to dependencies
Fixes the following nodetool issue on CentOS 7:

 [root@m2 apache-cassandra-2.1.9]# nodetool
 Traceback (most recent call last):
   File "/usr/bin/filter_cassandra_attributes.py", line 4, in <module>
     from yaml import load, dump, load_all
 ImportError: No module named yaml
 nodetool: Required values for option 'port' not provided
 See 'nodetool help' or 'nodetool help <command>'.

Spotted by Tomek.

Signed-off-by: Pekka Enberg <penberg@cloudius-systems.com>