build: Add generated Thrift sources to multi-Java build
The _build_multi_java build target did not include the Thrift-generated
sources, causing the following build failure:

    [javac] /home/penberg/src/scylla/scylla/tools/java/src/java/org/apache/cassandra/cql3/ResultSet.java:28: error: cannot find symbol
    [javac] import org.apache.cassandra.thrift.Column;
    [javac]                                   ^
    [javac]   symbol:   class Column
    [javac]   location: package org.apache.cassandra.thrift

Message-Id: <20201028071543.1208723-1-penberg@scylladb.com>