fix filter_cassandra_attributes.py python shebang
filter_cassandra_attributes.py is a python2 only script for now
so its shebang needs to specify this python2 dependency to avoid
breaking the scylla tools when the system default python is 3:

  File "/usr/bin/filter_cassandra_attributes.py", line 11
    print dump(dict(filter(lambda (a, b): a in cassandra_attributes, attributes.items())))
             ^
SyntaxError: invalid syntax

Signed-off-by: Alexys Jacob <ultrabug@gentoo.org>
Message-Id: <20170824151932.17801-1-ultrabug@gentoo.org>